---
version: '3'

services:
  app:
    image: golang:1.19
    volumes:
      - .:/app  # Mount local folder as app's root
    working_dir: /app
    command: ["go", "run", "./cmd/app"]
    environment:
      - TEST_DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}?sslmode=disable
    
  postgres:
    image: 'postgres:14.2'
    #    command: postgres -c 'max_connections=1024'
    ports:
      - 13000:5432

    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
